version: '3'

tasks:
  build-chordpo-lang:
    desc: Build ChordPro grammar artifacts
    cmds:
      - node src/frontend/logic/chordpo-lang/build.js

  build:
    desc: |
      Build the project for distribution. The site must be specified.
      SITE=floppydisk task build
      SITE=browserchords task build
    cmds:
      - |
        eval "$(node scripts/select-site.mjs)"
        rm -rf dist
        NODE_ENV=production SITE="$SITE" webpack
        SITE="$SITE" node scripts/build-docs.mjs

  build-docs:
    desc: |
      Build static docs into dist/docs. The site must be specified.
      SITE=floppydisk task build-docs
      SITE=browserchords task build-docs
    cmds:
      - |
        eval "$(node scripts/select-site.mjs)"
        SITE="$SITE" node scripts/build-docs.mjs

  check-updates:
    desc: Check for package updates
    cmds:
      - npx npm-check-updates

  start:
    desc: Start one of the Indie Web projects.
    cmds:
      - |
        eval "$(node scripts/select-site.mjs)"
        SITE="$SITE" task --parallel start-ts start-webpack start-docs-watch

  start-ts:
    desc: Start TypeScript in watch mode
    cmds:
      - tsc --noEmit --watch --project src/tsconfig.json

  start-webpack:
    desc: Start Webpack server for the selected site
    cmds:
      - NODE_ENV=development SITE=$SITE ./webpack.server.js

  start-docs-watch:
    desc: Watch docs and rebuild static output on changes
    cmds:
      - |
        SITE="$SITE" nodemon \
          --watch docs \
          --watch data/common/shared.css \
          --ext md,html,css \
          --exec "node scripts/build-docs.mjs"

  start-server:
    desc: Start the server in development mode
    dir: src/server
    cmds:
      - '[ -d "node_modules" ] || npm install'
      - npm run start-dev

  lint:
    desc: Run ESLint linter
    cmds:
      - eslint "*.{js,mjs}" 'src'

  bundle-size:
    desc: Calculate the bundle size
    cmds:
      - echo "Bundling webpack"
      - NODE_ENV=production webpack --json > stats.json
      - ./node_modules/.bin/webpack-bundle-analyzer stats.json

  ts:
    desc: TypeScript compilation check
    cmds:
      - tsc --noEmit --project src/frontend/tsconfig.json
      - tsc --noEmit --project src/server/tsconfig.json
      - tsc --noEmit --project src/shared/tsconfig.json

  test:
    desc: Run tests
    cmds:
      - env NODE_ENV=test jest

  test-coverage:
    desc: Run tests with coverage report
    cmds:
      - "env NODE_ENV=test jest --coverage"
      - "echo 'View coverage report at: ./coverage/lcov-report/'"

  test-all:
    desc: Run lint, TypeScript check, and tests
    cmds:
      - task: lint
      - task: ts
      - task: test

  docker-server:
    desc: Run the server from docker.
    dir: src/server/docker
    cmds:
      # Add --progress=plain to debug the build.
      - docker compose build
      - docker compose up

  docker-publish:
    desc: Publish the docker image for the server.
    cmds:
      - ./src/server/docker/publish.sh
