// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {line, chord} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'OQoOTOOOOOO'#Ca'#CaOvOWO'#CcO{OWO'#CiO!QOYO'#CkO!YOSO'#CjO!nOSO'#CjO#SOYO'#CpO#[O`O'#CqO!zOSO'#CsQQOTOOO#jOSOOO#oOWO,58}O#wOWO,59TOOOO,59V,59VO#|OWO,59VOOOO'#Ct'#CtO$ROSO,59UOOOP,59_,59_OOOQ'#Cu'#CuO$gOQO'#CuO$lOYO,59[OOOO,59],59]O$zOWO,59]OOOP-E6q-E6qQ%VOTOOOOOO1G.i1G.iO%^OpO1G.iO%fOpO1G.oOOOO1G.q1G.qOOOO-E6r-E6rOOOQ,59a,59aO%nOUO1G.vOOOQ-E6s-E6sOOOO1G.w1G.wOOOO'#Cb'#CbO%yOSOOO&OOWO7+$TO&TOpO7+$TOOOO7+$Z7+$ZO&YOpO7+$ZQQOTOOOOOO<<Go<<GoO&_OWO<<GoOOOO<<Gu<<GuOOOOAN=ZAN=Z",
  stateData: "&g~OPXOQWOWQO`SObTOcTOkXOnVOoRO~OlPO~PQOX[O~OX]O~OR_Oa^O~OWQO`SOb`Oc`Op^Xr^X~OWQO`SOb`Oc`OpbOrbO~ORcOqdO~OYfOfgOpeXreX~OpiO~OYkO[jO~OYlO~OamO~OWQO`SOb`Oc`Op^ar^a~ORoO~ORcOqpOpdarda~OYrOpearea~OmsO~PQOZuOqvO~OZwOqxO~ORoOpdirdi~OpyO~O[zO~OZ{O~OZ|O~O[}O~OqZ~",
  goto: "!tjPPPPPknqPPPPP||!SPPPP||P!_!g!nRZORtiWUOYiyV`TUaXXOYiyWTOYiyV`TUaUYOiyRhYSaTURnaQeVRqe",
  nodeNames: "⚠ Comment SectionName Chord Song Title Author Directive { DirectiveName : DirectiveValue } Directive Lyrics InlineChord [ ] Lyric Separator ChordLine Section SectionText",
  maxTerm: 34,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "2p~RjOX!sXY*TYZ+eZ]!s]^+j^p!spq*Tq![!s![!]+p!]!c!s!c!},o!}#O.S#O#P/O#P#Q/l#Q#R!s#R#S,o#S#T!s#T#o,o#o#p0s#p#q!s#q#r1o#r;'S!s;'S;=`)}<%l~!s~O!s~~2k]!|^bPfSZWOY!sZ]!s^![!s![!]#x!]!}!s!}#O&t#O#P'n#P#o!s#o#p&t#p#q!s#q#r(}#r;'S!s;'S;=`)}<%lO!sX$P[bPZWOY#xZ]#x^!}#x!}#O$u#O#P%d#P#o#x#o#p$u#p#q#x#q#r%|#r;'S#x;'S;=`&n<%lO#xW$zWZWOY$uZ]$u^#O$u#O#P%d#P#q$u#r;'S$u;'S;=`%v<%lO$uW%gTOY$uZ]$u^;'S$u;'S;=`%v<%lO$uW%yP;=`<%l$uP&RVbPOY%|Z]%|^!}%|#P#o%|#p;'S%|;'S;=`&h<%lO%|P&kP;=`<%l%|X&qP;=`<%l#x[&{ZfSZWOY&tZ]&t^![&t![!]$u!]#O&t#O#P'n#P#q&t#q#r(`#r;'S&t;'S;=`(Y<%lO&t['sVfSOY&tZ]&t^![&t![!]$u!];'S&t;'S;=`(Y<%lO&t[(]P;=`<%l&tS(eUfSOY(`Z](`^![(`!];'S(`;'S;=`(w<%lO(`S(zP;=`<%l(`T)UZbPfSOY(}Z](}^![(}![!]%|!]!}(}!}#P(`#P#o(}#o#p(`#p;'S(};'S;=`)w<%lO(}T)zP;=`<%l(}]*QP;=`<%l!s_*`abPfSqYZWOX!sXY*TZ]!s^p!spq*Tq![!s![!]#x!]!}!s!}#O&t#O#P'n#P#o!s#o#p&t#p#q!s#q#r(}#r;'S!s;'S;=`)}<%lO!s~+jOp~~+mPYZ+e_+y[YUbPZWOY#xZ]#x^!}#x!}#O$u#O#P%d#P#o#x#o#p$u#p#q#x#q#r%|#r;'S#x;'S;=`&n<%lO#x_,zbXQbPfSZWOY!sZ]!s^![!s![!]#x!]!c!s!c!},o!}#O&t#O#P'n#P#R!s#R#S,o#S#T!s#T#o,o#o#p&t#p#q!s#q#r(}#r;'S!s;'S;=`)}<%lO!s].]Z`PfSZWOY&tZ]&t^![&t![!]$u!]#O&t#O#P'n#P#q&t#q#r(`#r;'S&t;'S;=`(Y<%lO&t]/VVfScPOY&tZ]&t^![&t![!]$u!];'S&t;'S;=`(Y<%lO&t_/w^aQbPfSZWOY!sZ]!s^![!s![!]#x!]!}!s!}#O&t#O#P'n#P#o!s#o#p&t#p#q!s#q#r(}#r;'S!s;'S;=`)}<%lO!s]0|ZWPfSZWOY&tZ]&t^![&t![!]$u!]#O&t#O#P'n#P#q&t#q#r(`#r;'S&t;'S;=`(Y<%lO&tV1xZ[QbPfSOY(}Z](}^![(}![!]%|!]!}(}!}#P(`#P#o(}#o#p(`#p;'S(};'S;=`)w<%lO(}~2pOr~",
  tokenizers: [line, chord, 0, 1, 2, 3],
  topRules: {"Song":[0,4]},
  dialects: {noTitle: 0},
  tokenPrec: 250
})
